import type { ChapterManifest, CourseManifest, LocalizedText } from "./types";

const text = (zh: string, en: string): LocalizedText => ({ zh, en });

export const courseManifests: CourseManifest[] = [
  {
    id: "statistics",
    title: text("统计学学习路径", "Statistics learning path"),
    description: text(
      "从数据、概率与抽样出发，逐步学习统计推断、回归及更广泛的统计方法。",
      "Progress from data, probability, and sampling to inference, regression, and broader statistical methods.",
    ),
    chapterIds: [
      "statistics-introduction",
      "data-and-sampling",
      "data-visualization",
      "descriptive-statistics",
      "probability-and-random-variables",
      "probability-distributions",
      "central-limit-theorem",
      "parameter-estimation",
      "hypothesis-testing",
      "regression-analysis",
      "categorical-data",
      "nonparametric-tests",
      "time-series",
    ],
  },
  {
    id: "statistical-simulation",
    title: text("统计模拟探索", "Statistical simulation explorer"),
    description: text(
      "用可重复的计算实验理解抽样、重抽样与 Monte Carlo 方法。",
      "Use reproducible computational experiments to study sampling, resampling, and Monte Carlo methods.",
    ),
    chapterIds: ["simulation-laboratory"],
  },
];

export const chapterManifests: ChapterManifest[] = [
  {
    id: "statistics-introduction",
    courseId: "statistics",
    order: 0,
    title: text("00 统计学导论", "00 Introduction to statistics"),
    description: text("认识统计问题、数据证据与不确定性。", "Frame statistical questions, evidence, and uncertainty."),
    learningObjectives: [text("区分总体、样本、参数和统计量。", "Distinguish populations, samples, parameters, and statistics.")],
    topicIds: ["statistics-foundations"],
  },
  {
    id: "data-and-sampling",
    courseId: "statistics",
    order: 1,
    title: text("01 数据与抽样", "01 Data and sampling"),
    description: text("理解变量、数据结构与抽样设计。", "Understand variables, data structures, and sampling designs."),
    learningObjectives: [text("识别数据类型并评价抽样质量。", "Identify data types and evaluate sampling quality.")],
    topicIds: ["data-and-variables", "sampling-methods"],
  },
  {
    id: "data-visualization",
    courseId: "statistics",
    order: 2,
    title: text("02 数据可视化", "02 Data visualization"),
    description: text("用图形探索分布、关系与异常。", "Explore distributions, relationships, and anomalies with graphics."),
    learningObjectives: [text("根据变量类型选择合适图形。", "Choose graphics that match the variable types.")],
    topicIds: ["visual-encoding", "histograms"],
  },
  {
    id: "descriptive-statistics",
    courseId: "statistics",
    order: 3,
    title: text("03 描述统计", "03 Descriptive statistics"),
    description: text("用数值概括分布的中心、离散与形状。", "Summarize a distribution's centre, spread, and shape."),
    learningObjectives: [text("计算并解释常用描述统计量。", "Calculate and interpret common descriptive statistics.")],
    topicIds: ["descriptive-statistics", "standardization"],
  },
  {
    id: "probability-and-random-variables",
    courseId: "statistics",
    order: 4,
    title: text("04 概率与随机变量", "04 Probability and random variables"),
    description: text("建立随机现象的概率语言。", "Build a probability language for random phenomena."),
    learningObjectives: [text("解释随机变量及其概率模型。", "Explain random variables and their probability models.")],
    topicIds: ["probability-foundations", "random-variables"],
  },
  {
    id: "probability-distributions",
    courseId: "statistics",
    order: 5,
    title: text("05 概率分布", "05 Probability distributions"),
    description: text("比较常见离散与连续分布。", "Compare common discrete and continuous distributions."),
    learningObjectives: [text("根据情境选择并解释概率分布。", "Select and interpret probability distributions for a context.")],
    topicIds: ["probability-distributions", "normal-distribution", "t-distribution"],
  },
  {
    id: "central-limit-theorem",
    courseId: "statistics",
    order: 6,
    title: text("06 中心极限定理", "06 Central limit theorem"),
    description: text("连接总体、抽样分布与正态近似。", "Connect populations, sampling distributions, and normal approximations."),
    learningObjectives: [text("区分样本量与重复抽样次数。", "Distinguish sample size from the number of repeated samples.")],
    topicIds: ["sampling-distributions", "central-limit-theorem"],
  },
  {
    id: "parameter-estimation",
    courseId: "statistics",
    order: 7,
    title: text("07 参数估计", "07 Parameter estimation"),
    description: text("用点估计与区间估计表达不确定性。", "Express uncertainty with point and interval estimates."),
    learningObjectives: [text("正确解释置信区间的覆盖含义。", "Interpret the coverage meaning of confidence intervals.")],
    topicIds: ["point-estimation", "confidence-interval"],
  },
  {
    id: "hypothesis-testing",
    courseId: "statistics",
    order: 8,
    title: text("08 假设检验", "08 Hypothesis testing"),
    description: text("用证据、错误概率与功效评价统计假设。", "Evaluate statistical hypotheses using evidence, error rates, and power."),
    learningObjectives: [text("解释 p 值、显著性水平与两类错误。", "Explain p-values, significance levels, and both error types.")],
    topicIds: ["hypothesis-testing", "type-i-type-ii-errors", "anova"],
  },
  {
    id: "regression-analysis",
    courseId: "statistics",
    order: 9,
    title: text("09 回归分析", "09 Regression analysis"),
    description: text("刻画变量之间的线性关系并评价模型。", "Describe linear relationships and evaluate models."),
    learningObjectives: [text("拟合并解释一元线性回归。", "Fit and interpret simple linear regression.")],
    topicIds: ["correlation", "linear-regression"],
  },
  {
    id: "categorical-data",
    courseId: "statistics",
    order: 10,
    title: text("10 分类数据与卡方检验", "10 Categorical data and chi-square tests"),
    description: text("分析计数、比例与列联表。", "Analyse counts, proportions, and contingency tables."),
    learningObjectives: [text("使用卡方方法检验分类变量关系。", "Use chi-square methods to test categorical relationships.")],
    topicIds: ["categorical-data", "chi-square-test"],
  },
  {
    id: "nonparametric-tests",
    courseId: "statistics",
    order: 11,
    title: text("11 非参数检验", "11 Nonparametric tests"),
    description: text("在参数假设不适用时使用秩与重抽样方法。", "Use rank and resampling methods when parametric assumptions do not apply."),
    learningObjectives: [text("根据数据条件选择非参数检验。", "Choose a nonparametric test for the data conditions.")],
    topicIds: ["nonparametric-tests"],
  },
  {
    id: "time-series",
    courseId: "statistics",
    order: 12,
    title: text("12 时间序列", "12 Time series"),
    description: text("识别随时间变化的趋势、季节性与相关结构。", "Identify trend, seasonality, and dependence over time."),
    learningObjectives: [text("描述时间序列的基本组成。", "Describe the basic components of a time series.")],
    topicIds: ["time-series"],
  },
  {
    id: "simulation-laboratory",
    courseId: "statistical-simulation",
    order: 0,
    title: text("统计模拟", "Statistical simulation"),
    description: text("独立探索 Monte Carlo、重抽样与序贯模拟方法。", "Explore Monte Carlo, resampling, and sequential simulation methods."),
    learningObjectives: [text("用模拟设计、诊断并改进统计计算实验。", "Design, diagnose, and improve statistical computing experiments.")],
    topicIds: [
      "simulation-foundations",
      "monte-carlo",
      "bootstrap-and-permutation",
      "mcmc",
      "gibbs-sampling",
      "metropolis-hastings",
      "importance-sampling",
      "sequential-monte-carlo",
      "variance-reduction",
    ],
  },
];
